name: Deno CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build docker-compose
        run: docker-compose up -d
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
      - name: runBackend
        run: |
          deno run -c tsconfig.json --allow-net --allow-read --allow-write --allow-env --unstable src/Apps/Membership/backend/start.ts