name: Deno CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
      - name: Launch MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: ${{ matrix.mongodb-version }}
      - name: runBackend
        run: |
          deno run -c tsconfig.json --watch --allow-net --allow-read --allow-write --allow-env --unstable src/Apps/Membership/backend/start.ts


