name: Deno CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
      - name: ls
        run: ls src
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: samuelguzmanajala--eno-est # the name of the project on Deno Deploy
          entrypoint: index.ts # the entrypoint to deploy