name: Deno CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: ls
        run: ls -a
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: testdeno # the name of the project on Deno Deploy
          entrypoint: main.ts # the entrypoint to deploy
      - name: ls2
        run: ls -a