name: Deno CI

on: 
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.8.2]

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v3
      - name: Use Deno version ${{matrix.deno-version}}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Lint Deno
        run: deno fmt --check
      - name: Build Deno
        run: deno run --reload --allow-all --import-map=import_map.json src/Apps/Membership/backend/index.ts
      - name: Test Deno
        run: deno test --allow-none --import-map=import_map.json